# EV Charging Infrastructure Planning & Demand Prediction

## Notebook 02 : EV Registration Data Preprocessing

### Business Objective

The objective of this notebook is to clean and preprocess the EV registration dataset. This dataset will be used to analyze EV adoption trends, estimate future EV growth, and support charging demand prediction.

In [24]:
# ==========================================================
#   Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)

In [25]:
# ==========================================================
#   Load EV Registration Dataset
# ==========================================================

ev = pd.read_excel("../data/raw/ev_registration.xlsx")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [26]:
ev.shape

(4500, 9)

In [27]:
ev.head()

   Year    Month        State District/City    2W   3W   4W  Bus  Goods
0  2021  January  Maharashtra        Mumbai  1945  364  273   24    109
1  2021  January  Maharashtra          Pune  2036  381  286   25    114
2  2021  January  Maharashtra        Nagpur  1480  277  208   18     83
3  2021  January  Maharashtra        Nashik  1576  295  221   19     88
4  2021  January  Maharashtra    Aurangabad  2014  377  283   25    113

In [28]:
ev.columns.tolist()

['Year', 'Month', 'State', 'District/City', '2W', '3W', '4W', 'Bus', 'Goods']

In [29]:
ev.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           4500 non-null   int64
 1   Month          4500 non-null   str
 2   State          4500 non-null   str
 3   District/City  4500 non-null   str
 4   2W             4500 non-null   int64
 5   3W             4500 non-null   int64
 6   4W             4500 non-null   int64
 7   Bus            4500 non-null   int64
 8   Goods          4500 non-null   int64
dtypes: int64(6), str(3)
memory usage: 416.8 KB

In [30]:
ev.isnull().sum()

Year             0
Month            0
State            0
District/City    0
2W               0
3W               0
4W               0
Bus              0
Goods            0
dtype: int64

In [31]:
ev.duplicated().sum()

np.int64(0)

In [32]:
ev.dtypes

Year             int64
Month              str
State              str
District/City      str
2W               int64
3W               int64
4W               int64
Bus              int64
Goods            int64
dtype: object

In [33]:
ev.rename(columns={
    "District/City":"City"
}, inplace=True)

In [34]:
ev["State"] = ev["State"].str.strip()
ev["City"] = ev["City"].str.strip()

In [35]:
ev["State"] = ev["State"].str.title()
ev["City"] = ev["City"].str.title()
ev["Month"] = ev["Month"].str.title()

In [36]:
numeric_cols = [
    "Year",
    "2W",
    "3W",
    "4W",
    "Bus",
    "Goods"
]

ev[numeric_cols] = ev[numeric_cols].apply(pd.to_numeric)

In [37]:
ev["Total_EV"] = (
    ev["2W"] +
    ev["3W"] +
    ev["4W"] +
    ev["Bus"] +
    ev["Goods"]
)

In [38]:
month_map = {
    "January":1,
    "February":2,
    "March":3,
    "April":4,
    "May":5,
    "June":6,
    "July":7,
    "August":8,
    "September":9,
    "October":10,
    "November":11,
    "December":12
}

ev["Month_No"] = ev["Month"].map(month_map)

In [39]:
ev = ev[
[
"Year",
"Month",
"Month_No",
"State",
"City",
"2W",
"3W",
"4W",
"Bus",
"Goods",
"Total_EV"
]
]

In [40]:
ev.describe()

,Year,Month_No,2W,3W,4W,Bus,Goods,Total_EV
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,2023.000000,6.500000,2019.019778,378.159333,283.493778,24.739556,113.101333,2818.513778
std,1.414371,3.452436,823.008137,154.314243,115.737655,10.292119,46.296669,1149.643409
min,2021.000000,1.000000,835.000000,156.000000,117.000000,10.000000,46.000000,1164.000000
25%,2022.000000,3.750000,1415.750000,265.000000,199.000000,17.000000,79.000000,1975.750000
50%,2023.000000,6.500000,1862.000000,349.000000,261.000000,23.000000,104.000000,2599.000000
75%,2024.000000,9.250000,2397.000000,449.000000,337.000000,29.000000,134.000000,3346.000000
max,2025.000000,12.000000,5494.000000,1030.000000,772.000000,68.000000,309.000000,7673.000000

In [41]:
ev.head()

,Year,Month,Month_No,State,City,2W,3W,4W,Bus,Goods,Total_EV
0,2021,January,1,Maharashtra,Mumbai,1945,364,273,24,109,2715
1,2021,January,1,Maharashtra,Pune,2036,381,286,25,114,2842
2,2021,January,1,Maharashtra,Nagpur,1480,277,208,18,83,2066
3,2021,January,1,Maharashtra,Nashik,1576,295,221,19,88,2199
4,2021,January,1,Maharashtra,Aurangabad,2014,377,283,25,113,2812

In [42]:
ev.shape

(4500, 11)

In [43]:
ev.to_csv(
    "../data/processed/ev_registration_clean.csv",
    index=False
)