# EV Charging Infrastructure Planning & Demand Prediction

## Notebook 03 : Station Master Data Preprocessing

### Business Objective

The objective of this notebook is to clean and preprocess the charging station master dataset. This dataset contains charging station information that will be used for charging demand analysis, waiting time prediction, station utilization analysis, and business recommendations.

In [19]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [20]:
# ==========================================================
# Load Station Master Dataset
# ==========================================================

station = pd.read_excel("../data/raw/station_master.xlsx")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [21]:
station.shape

(129, 20)

In [22]:
station.head()

,Station_ID,Station_Name,State,City,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status
0,ST0001,Mumbai EV Hub 1,Maharashtra,Mumbai,9.4803,83.0511,Private,Ather Grid,AC,23,6,9,8,2021,18,No,Yes,Yes,6807,Active
1,ST0002,Mumbai EV Hub 2,Maharashtra,Mumbai,12.6151,83.3677,Private,Statiq,AC,16,3,4,9,2021,60,Yes,No,No,8062,Active
2,ST0003,Mumbai EV Hub 3,Maharashtra,Mumbai,31.6198,87.3191,Public,Ather Grid,Mixed,14,4,2,8,2021,39,No,Yes,Yes,10942,Active
3,ST0004,Pune EV Hub 1,Maharashtra,Pune,24.0721,82.3979,Private,Tata Power,Mixed,14,7,2,5,2021,59,Yes,No,No,1300,Active
4,ST0005,Pune EV Hub 2,Maharashtra,Pune,31.1455,87.2060,Public,Ather Grid,AC,15,2,8,5,2021,11,Yes,No,No,2164,Active

In [23]:
station.columns.tolist()

['Station_ID',
 'Station_Name',
 'State',
 'City',
 'Latitude',
 'Longitude',
 'Station_Type',
 'Operator',
 'Charger_Type',
 'Total_Chargers',
 'AC_Chargers',
 'DC_Chargers',
 'Fast_Chargers',
 'Installation_Year',
 'Parking_Capacity',
 'Nearby_Highway',
 'Nearby_Mall',
 'Nearby_Hospital',
 'Nearby_EV_Population',
 'Status']

In [24]:
station.info()

<class 'pandas.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Station_ID            129 non-null    str
 1   Station_Name          129 non-null    str
 2   State                 129 non-null    str
 3   City                  129 non-null    str
 4   Latitude              129 non-null    float64
 5   Longitude             129 non-null    float64
 6   Station_Type          129 non-null    str
 7   Operator              129 non-null    str
 8   Charger_Type          129 non-null    str
 9   Total_Chargers        129 non-null    int64
 10  AC_Chargers           129 non-null    int64
 11  DC_Chargers           129 non-null    int64
 12  Fast_Chargers         129 non-null    int64
 13  Installation_Year     129 non-null    int64
 14  Parking_Capacity      129 non-null    int64
 15  Nearby_Highway        129 non-null    str
 16  Nearby_Mall           129 non-null    str
 17  Nearby_Hospital       129 non-null    str
 18  Nearby_EV_Population  129 non-null    int64
 19  Status                129 non-null    str
dtypes: float64(2), int64(7), str(11)
memory usage: 29.4 KB

In [25]:
station.describe(include="all")

,Station_ID,Station_Name,State,City,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status
count,129,129,129,129,129.000000,129.000000,129,129,129,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129,129,129,129.000000,129
unique,129,129,10,34,NaN,NaN,3,5,3,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,1
top,ST0001,Mumbai EV Hub 1,Karnataka,Nagpur,NaN,NaN,Private,Ather Grid,Mixed,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Yes,NaN,Active
freq,1,1,19,5,NaN,NaN,45,30,45,NaN,NaN,NaN,NaN,NaN,NaN,69,68,66,NaN,129
mean,NaN,NaN,NaN,NaN,20.158666,80.930795,NaN,NaN,NaN,14.674419,4.472868,5.813953,4.387597,2022.813953,34.271318,NaN,NaN,NaN,6370.465116,NaN
std,NaN,NaN,NaN,NaN,7.804954,4.934844,NaN,NaN,NaN,5.420105,2.531296,3.574579,3.233878,1.412928,15.397723,NaN,NaN,NaN,3256.596467,NaN
min,NaN,NaN,NaN,NaN,8.082400,72.303800,NaN,NaN,NaN,6.000000,2.000000,2.000000,1.000000,2021.000000,10.000000,NaN,NaN,NaN,1090.000000,NaN
25%,NaN,NaN,NaN,NaN,12.963800,76.373400,NaN,NaN,NaN,10.000000,2.000000,3.000000,2.000000,2022.000000,19.000000,NaN,NaN,NaN,3368.000000,NaN
50%,NaN,NaN,NaN,NaN,19.899200,81.573100,NaN,NaN,NaN,15.000000,4.000000,5.000000,4.000000,2023.000000,34.000000,NaN,NaN,NaN,6288.000000,NaN
75%,NaN,NaN,NaN,NaN,27.215600,85.197300,NaN,NaN,NaN,19.000000,6.000000,8.000000,6.000000,2024.000000,48.000000,NaN,NaN,NaN,8989.000000,NaN
max,NaN,NaN,NaN,NaN,32.922100,88.452900,NaN,NaN,NaN,24.000000,12.000000,19.000000,16.000000,2025.000000,60.000000,NaN,NaN,NaN,11730.000000,NaN

In [26]:
station.isnull().sum()

Station_ID              0
Station_Name            0
State                   0
City                    0
Latitude                0
Longitude               0
Station_Type            0
Operator                0
Charger_Type            0
Total_Chargers          0
AC_Chargers             0
DC_Chargers             0
Fast_Chargers           0
Installation_Year       0
Parking_Capacity        0
Nearby_Highway          0
Nearby_Mall             0
Nearby_Hospital         0
Nearby_EV_Population    0
Status                  0
dtype: int64

In [27]:
station.duplicated().sum()

np.int64(0)

In [28]:
station.dtypes

Station_ID                  str
Station_Name                str
State                       str
City                        str
Latitude                float64
Longitude               float64
Station_Type                str
Operator                    str
Charger_Type                str
Total_Chargers            int64
AC_Chargers               int64
DC_Chargers               int64
Fast_Chargers             int64
Installation_Year         int64
Parking_Capacity          int64
Nearby_Highway              str
Nearby_Mall                 str
Nearby_Hospital             str
Nearby_EV_Population      int64
Status                      str
dtype: object

In [29]:
text_columns = station.select_dtypes(include="object").columns

for col in text_columns:
    station[col] = station[col].str.strip()

In [30]:
for col in text_columns:
    station[col] = station[col].str.title()

In [31]:
# ==========================================================
# Check Unique Values
# ==========================================================

print("Unique States :", station["State"].nunique())
print("Unique Cities :", station["City"].nunique())

print("\nOperator Distribution")
print(station["Operator"].value_counts())

print("\nStatus Distribution")
print(station["Status"].value_counts())

print("\nStation Type Distribution")
print(station["Station_Type"].value_counts())

print("\nCharger Type Distribution")
print(station["Charger_Type"].value_counts())

Unique States : 10
Unique Cities : 34

Operator Distribution
Operator
Ather Grid    30
Statiq        27
Jio-Bp        27
Chargezone    26
Tata Power    19
Name: count, dtype: int64

Status Distribution
Status
Active    129
Name: count, dtype: int64

Station Type Distribution
Station_Type
Private    45
Highway    44
Public     40
Name: count, dtype: int64

Charger Type Distribution
Charger_Type
Mixed    45
Ac       42
Dc       42
Name: count, dtype: int64

In [32]:
station["Fast_Charger_Ratio"] = (
    station["Fast_Chargers"] /
    station["Total_Chargers"]
)

In [33]:
station["DC_Ratio"] = (
    station["DC_Chargers"] /
    station["Total_Chargers"]
)

In [34]:
station["Station_Age"] = (
    2025 -
    station["Installation_Year"]
)

In [35]:
station["Utilization_Level"] = pd.cut(
    station["Nearby_EV_Population"],
    bins=[0,5000,15000,30000,100000],
    labels=["Low","Medium","High","Very High"]
)

In [36]:
station.to_csv(
    "../data/processed/station_master_clean.csv",
    index=False
)