# EV Charging Infrastructure Planning & Demand Prediction

## Notebook 04 : Station Usage Data Preprocessing

### Business Objective

The objective of this notebook is to clean and preprocess the station usage dataset. This dataset will be used to analyze charging sessions, waiting time, station utilization, and charging demand for business and customer recommendations.

In [1]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
# ==========================================================
# Load Dataset
# ==========================================================

usage = pd.read_excel("../data/raw/station_usage.xlsx")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
print("Shape :", usage.shape)

usage.head()

Shape : (7740, 18)

,Station_ID,Year,Month,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Utilization_%,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level
0,ST0001,2021,January,208,72,12,39,6,98800,47.5,1,4,1086800,4.1,5200,5104,96,Low
1,ST0001,2021,February,264,92,16,48,7,199056,64.9,4,12,3184896,4.5,6864,6599,265,Medium
2,ST0001,2021,March,192,67,21,52,7,144768,78.2,1,3,1592448,3.8,4992,4889,103,Medium
3,ST0001,2021,April,211,73,20,54,8,159516,66.6,4,12,2233224,4.1,5908,5810,98,Medium
4,ST0001,2021,May,119,41,22,32,6,110670,78.7,2,10,1770720,4.0,3570,3468,102,Medium

In [4]:
usage.columns.tolist()

['Station_ID',
 'Year',
 'Month',
 'Avg_Daily_Users',
 'Peak_Hour_Users',
 'Avg_Wait_Time_Min',
 'Avg_Charging_Time_Min',
 'Queue_Length',
 'Energy_Delivered_kWh',
 'Utilization_%',
 'Fault_Count',
 'Downtime_Hours',
 'Revenue_INR',
 'Customer_Rating',
 'Sessions',
 'Completed_Sessions',
 'Cancelled_Sessions',
 'Demand_Level']

In [5]:
usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 7740 entries, 0 to 7739
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Station_ID             7740 non-null   str
 1   Year                   7740 non-null   int64
 2   Month                  7740 non-null   str
 3   Avg_Daily_Users        7740 non-null   int64
 4   Peak_Hour_Users        7740 non-null   int64
 5   Avg_Wait_Time_Min      7740 non-null   int64
 6   Avg_Charging_Time_Min  7740 non-null   int64
 7   Queue_Length           7740 non-null   int64
 8   Energy_Delivered_kWh   7740 non-null   int64
 9   Utilization_%          7740 non-null   float64
 10  Fault_Count            7740 non-null   int64
 11  Downtime_Hours         7740 non-null   int64
 12  Revenue_INR            7740 non-null   int64
 13  Customer_Rating        7740 non-null   float64
 14  Sessions               7740 non-null   int64
 15  Completed_Sessions     7740 non-null   int64
 16  Cancelled_Sessions     7740 non-null   int64
 17  Demand_Level           7740 non-null   str
dtypes: float64(2), int64(13), str(3)
memory usage: 1.2 MB

In [6]:
usage.describe(include="all")

,Station_ID,Year,Month,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Utilization_%,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level
count,7740,7740.000000,7740,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7.740000e+03,7740.000000,7740.000000,7740.000000,7740.000000,7740
unique,129,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,ST0001,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medium
freq,60,NaN,645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3786
mean,NaN,2023.000000,NaN,186.412403,64.760853,17.791214,42.448837,5.579974,135858.131266,71.139457,1.981783,5.907623,1.700174e+06,4.192623,5035.872093,4922.940568,112.931525,NaN
std,NaN,1.414305,NaN,95.218063,33.324865,3.604110,7.570564,1.488878,77248.313021,12.476687,1.414416,5.408771,1.034387e+06,0.339540,2601.400796,2545.784807,80.539964,NaN
min,NaN,2021.000000,NaN,30.000000,10.000000,9.000000,30.000000,2.000000,15066.000000,45.000000,0.000000,0.000000,1.788480e+05,3.500000,720.000000,706.000000,6.000000,NaN
25%,NaN,2022.000000,NaN,113.000000,39.000000,15.000000,36.000000,4.000000,76880.000000,61.100000,1.000000,2.000000,9.287900e+05,3.900000,3024.000000,2957.000000,53.000000,NaN
50%,NaN,2023.000000,NaN,169.000000,59.000000,18.000000,42.000000,6.000000,119986.500000,71.100000,2.000000,4.000000,1.464340e+06,4.200000,4560.000000,4459.000000,93.000000,NaN
75%,NaN,2024.000000,NaN,243.000000,85.000000,20.000000,49.000000,7.000000,178137.750000,81.400000,3.000000,9.000000,2.213253e+06,4.500000,6552.000000,6402.250000,152.000000,NaN
max,NaN,2025.000000,NaN,593.000000,207.000000,27.000000,55.000000,9.000000,526848.000000,97.000000,4.000000,20.000000,7.902720e+06,4.900000,17197.000000,16855.000000,651.000000,NaN

In [7]:
print("Missing Values")

print(usage.isnull().sum())

Missing Values
Station_ID               0
Year                     0
Month                    0
Avg_Daily_Users          0
Peak_Hour_Users          0
Avg_Wait_Time_Min        0
Avg_Charging_Time_Min    0
Queue_Length             0
Energy_Delivered_kWh     0
Utilization_%            0
Fault_Count              0
Downtime_Hours           0
Revenue_INR              0
Customer_Rating          0
Sessions                 0
Completed_Sessions       0
Cancelled_Sessions       0
Demand_Level             0
dtype: int64

In [8]:
print("Duplicate Records :", usage.duplicated().sum())

Duplicate Records : 0

In [9]:
print(usage.dtypes)

Station_ID                   str
Year                       int64
Month                        str
Avg_Daily_Users            int64
Peak_Hour_Users            int64
Avg_Wait_Time_Min          int64
Avg_Charging_Time_Min      int64
Queue_Length               int64
Energy_Delivered_kWh       int64
Utilization_%            float64
Fault_Count                int64
Downtime_Hours             int64
Revenue_INR                int64
Customer_Rating          float64
Sessions                   int64
Completed_Sessions         int64
Cancelled_Sessions         int64
Demand_Level                 str
dtype: object

In [10]:
text_columns = usage.select_dtypes(include="object").columns

for col in text_columns:
    usage[col] = usage[col].str.strip()

In [11]:
for col in text_columns:
    usage[col] = usage[col].str.title()

In [12]:
print("Unique Stations :", usage["Station_ID"].nunique())

print("\nDemand Level")
print(usage["Demand_Level"].value_counts())

print("\nYears")
print(usage["Year"].unique())

print("\nMonths")
print(sorted(usage["Month"].unique()))

Unique Stations : 129

Demand Level
Demand_Level
Medium    3786
High      2214
Low       1740
Name: count, dtype: int64

Years
[2021 2022 2023 2024 2025]

Months
['April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September']

In [13]:
usage.to_csv(
    "../data/processed/station_usage_clean.csv",
    index=False
)

print("Station Usage Dataset Saved Successfully")

Station Usage Dataset Saved Successfully