# EV Charging Infrastructure Planning & Demand Prediction

## Notebook 08 : Feature Engineering

### Business Objective

The objective of this notebook is to prepare the master dataset for machine learning by handling missing values, encoding categorical variables, creating new features, selecting important features, and saving the final model-ready dataset.

In [19]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

pd.set_option("display.max_columns", None)

In [20]:
# ==========================================================
# Load Master Dataset
# ==========================================================

master = pd.read_csv("../data/processed/master_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [21]:
print(master.shape)

master.head()

(9955, 56)

,Year,State,City,Population,Month,Month_No,2W,3W,4W,Bus,Goods,Total_EV,Public_AC,Public_DC,Private,Highway_Fast,Total_Charging_Stations,Station_Utilization,Avg_Daily_Sessions,Station_ID,Station_Name,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status,Fast_Charger_Ratio,DC_Ratio,Station_Age,Utilization_Level,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Usage_Utilization,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level
0,2021,Andhra Pradesh,Visakhapatnam,2287676,January,1.0,961.0,180.0,135.0,12.0,54.0,1342.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,Andhra Pradesh,Visakhapatnam,2287676,February,2.0,1115.0,209.0,156.0,13.0,62.0,1555.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,Andhra Pradesh,Visakhapatnam,2287676,March,3.0,1142.0,214.0,160.0,14.0,64.0,1594.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Andhra Pradesh,Visakhapatnam,2287676,April,4.0,1131.0,212.0,159.0,14.0,63.0,1579.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Andhra Pradesh,Visakhapatnam,2287676,May,5.0,1093.0,205.0,153.0,13.0,61.0,1525.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
print(master.isnull().sum())

Year                          0
State                         0
City                          0
Population                    0
Month                       235
Month_No                    235
2W                          235
3W                          235
4W                          235
Bus                         235
Goods                       235
Total_EV                    235
Public_AC                  1355
Public_DC                  1355
Private                    1355
Highway_Fast               1355
Total_Charging_Stations    1355
Station_Utilization        1355
Avg_Daily_Sessions         1355
Station_ID                 2615
Station_Name               2615
Latitude                   2615
Longitude                  2615
Station_Type               2615
Operator                   2615
Charger_Type               2615
Total_Chargers             2615
AC_Chargers                2615
DC_Chargers                2615
Fast_Chargers              2615
Installation_Year          2615
Parking_Capacity           2615
Nearby_Highway             2615
Nearby_Mall                2615
Nearby_Hospital            2615
Nearby_EV_Population       2615
Status                     2615
Fast_Charger_Ratio         2615
DC_Ratio                   2615
Station_Age                2615
Utilization_Level          2615
Avg_Daily_Users            2635
Peak_Hour_Users            2635
Avg_Wait_Time_Min          2635
Avg_Charging_Time_Min      2635
Queue_Length               2635
Energy_Delivered_kWh       2635
Usage_Utilization          2635
Fault_Count                2635
Downtime_Hours             2635
Revenue_INR                2635
Customer_Rating            2635
Sessions                   2635
Completed_Sessions         2635
Cancelled_Sessions         2635
Demand_Level               2635
dtype: int64

In [23]:
numeric_columns = master.select_dtypes(include=np.number).columns

master[numeric_columns] = master[numeric_columns].fillna(0)

In [24]:
categorical_columns = master.select_dtypes(include="object").columns

master[categorical_columns] = master[categorical_columns].fillna("Unknown")

In [25]:
print(master.isnull().sum())

Year                       0
State                      0
City                       0
Population                 0
Month                      0
Month_No                   0
2W                         0
3W                         0
4W                         0
Bus                        0
Goods                      0
Total_EV                   0
Public_AC                  0
Public_DC                  0
Private                    0
Highway_Fast               0
Total_Charging_Stations    0
Station_Utilization        0
Avg_Daily_Sessions         0
Station_ID                 0
Station_Name               0
Latitude                   0
Longitude                  0
Station_Type               0
Operator                   0
Charger_Type               0
Total_Chargers             0
AC_Chargers                0
DC_Chargers                0
Fast_Chargers              0
Installation_Year          0
Parking_Capacity           0
Nearby_Highway             0
Nearby_Mall                0
Nearby_Hospital            0
Nearby_EV_Population       0
Status                     0
Fast_Charger_Ratio         0
DC_Ratio                   0
Station_Age                0
Utilization_Level          0
Avg_Daily_Users            0
Peak_Hour_Users            0
Avg_Wait_Time_Min          0
Avg_Charging_Time_Min      0
Queue_Length               0
Energy_Delivered_kWh       0
Usage_Utilization          0
Fault_Count                0
Downtime_Hours             0
Revenue_INR                0
Customer_Rating            0
Sessions                   0
Completed_Sessions         0
Cancelled_Sessions         0
Demand_Level               0
dtype: int64

In [26]:
master["EV_Per_Station"] = (
    master["Total_EV"] /
    (master["Total_Charging_Stations"] + 1)
)

In [27]:
master["Chargers_Per_Station"] = (
    master["Total_Chargers"] /
    (master["Total_Charging_Stations"] + 1)
)

In [28]:
master["Revenue_Per_Session"] = (
    master["Revenue_INR"] /
    (master["Sessions"] + 1)
)

In [29]:
master["Completion_Rate"] = (
    master["Completed_Sessions"] /
    (master["Sessions"] + 1)
)

In [30]:
master["Cancellation_Rate"] = (
    master["Cancelled_Sessions"] /
    (master["Sessions"] + 1)
)

In [31]:
master["Downtime_Percentage"] = (
    master["Downtime_Hours"] /
    720
) * 100

In [32]:
master["Queue_Per_User"] = (
    master["Queue_Length"] /
    (master["Avg_Daily_Users"] + 1)
)

In [33]:
categorical_columns = master.select_dtypes(include="object").columns

encoder = LabelEncoder()

for col in categorical_columns:
    master[col] = encoder.fit_transform(master[col])

In [34]:
print(master.columns.tolist())

['Year', 'State', 'City', 'Population', 'Month', 'Month_No', '2W', '3W', '4W', 'Bus', 'Goods', 'Total_EV', 'Public_AC', 'Public_DC', 'Private', 'Highway_Fast', 'Total_Charging_Stations', 'Station_Utilization', 'Avg_Daily_Sessions', 'Station_ID', 'Station_Name', 'Latitude', 'Longitude', 'Station_Type', 'Operator', 'Charger_Type', 'Total_Chargers', 'AC_Chargers', 'DC_Chargers', 'Fast_Chargers', 'Installation_Year', 'Parking_Capacity', 'Nearby_Highway', 'Nearby_Mall', 'Nearby_Hospital', 'Nearby_EV_Population', 'Status', 'Fast_Charger_Ratio', 'DC_Ratio', 'Station_Age', 'Utilization_Level', 'Avg_Daily_Users', 'Peak_Hour_Users', 'Avg_Wait_Time_Min', 'Avg_Charging_Time_Min', 'Queue_Length', 'Energy_Delivered_kWh', 'Usage_Utilization', 'Fault_Count', 'Downtime_Hours', 'Revenue_INR', 'Customer_Rating', 'Sessions', 'Completed_Sessions', 'Cancelled_Sessions', 'Demand_Level', 'EV_Per_Station', 'Chargers_Per_Station', 'Revenue_Per_Session', 'Completion_Rate', 'Cancellation_Rate', 'Downtime_Percentage', 'Queue_Per_User']

In [35]:
print(master.shape)

(9955, 63)

In [36]:
master.head()

,Year,State,City,Population,Month,Month_No,2W,3W,4W,Bus,Goods,Total_EV,Public_AC,Public_DC,Private,Highway_Fast,Total_Charging_Stations,Station_Utilization,Avg_Daily_Sessions,Station_ID,Station_Name,Latitude,Longitude,Station_Type,Operator,Charger_Type,Total_Chargers,AC_Chargers,DC_Chargers,Fast_Chargers,Installation_Year,Parking_Capacity,Nearby_Highway,Nearby_Mall,Nearby_Hospital,Nearby_EV_Population,Status,Fast_Charger_Ratio,DC_Ratio,Station_Age,Utilization_Level,Avg_Daily_Users,Peak_Hour_Users,Avg_Wait_Time_Min,Avg_Charging_Time_Min,Queue_Length,Energy_Delivered_kWh,Usage_Utilization,Fault_Count,Downtime_Hours,Revenue_INR,Customer_Rating,Sessions,Completed_Sessions,Cancelled_Sessions,Demand_Level,EV_Per_Station,Chargers_Per_Station,Revenue_Per_Session,Completion_Rate,Cancellation_Rate,Downtime_Percentage,Queue_Per_User
0,2021,0,113,2287676,4,1.0,961.0,180.0,135.0,12.0,54.0,1342.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,126,112,0.0,0.0,3,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0.0,1,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,51.615385,0.0,0.0,0.0,0.0,0.0,0.0
1,2021,0,113,2287676,3,2.0,1115.0,209.0,156.0,13.0,62.0,1555.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,126,112,0.0,0.0,3,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0.0,1,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,59.807692,0.0,0.0,0.0,0.0,0.0,0.0
2,2021,0,113,2287676,7,3.0,1142.0,214.0,160.0,14.0,64.0,1594.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,126,112,0.0,0.0,3,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0.0,1,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,61.307692,0.0,0.0,0.0,0.0,0.0,0.0
3,2021,0,113,2287676,0,4.0,1131.0,212.0,159.0,14.0,63.0,1579.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,126,112,0.0,0.0,3,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0.0,1,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,60.730769,0.0,0.0,0.0,0.0,0.0,0.0
4,2021,0,113,2287676,8,5.0,1093.0,205.0,153.0,13.0,61.0,1525.0,12.0,4.0,7.0,2.0,25.0,57.9,189.0,126,112,0.0,0.0,3,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0.0,1,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,58.653846,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
master.to_csv(
    "../data/processed/model_dataset.csv",
    index=False
)

print("="*50)
print("Feature Engineering Completed Successfully")
print("="*50)
print("Final Shape :", master.shape)

==================================================
Feature Engineering Completed Successfully
==================================================
Final Shape : (9955, 63)